### ISSUE TITLE
Filled Pause and output alignment for italian - version 1.8.0

### ISSUE THREAD

**Issue by yuriricci** [brigittebigi/sppas#6]
I would like to submit a problem for the following use case in SPPAS: forced alignment for italian language, with audio and transcription containing filled pauses. I denoted filled pauses in the transcription as 'eh'. They are recognized correctly at phoneme level; however the 'Activity' tier does not contain a segment indicating the filled pause, which would be very useful.

I made also a test with filled pauses denoted as 'euh' ( the French denotation, if I am correct ). In that case they are identified in the 'Activity' tier, but of course they are not present in the vocabulary, thus they are not properly handled at phoneme level.

Finally, I would suggest to clarify in the documentation, maybe in the enriched orthographic transcription explanation section, how to handle filled pauses for the different languages. It is already stated that they must be included, but not how to do it exactly ( I understood that from the resources section by examples )

Yuri

**Comment by brigittebigi** [comment]
right. Activities are language-dependent and I currently didn't created a specific list for each language. That's the reason the French 'euh' is working with your data: by default, SPPAS is using the French-based list of activities.
It will be fixed in the next version (at least for Italian).

For now, if it's urgent, you can add the line "euh [] e" in the pronunciation dictionary of Italian. It will solve the problem for your data. Quick and dark solution, but it works!

**Comment by yuriricci** [comment]
Thanks for the quick reply!
That's exactly the temp solution I already implemented ( euh [] fp ) and I confirm that the Activity tier is ok.
Anyway, I would like to congratulate for the application, it works very well :)
